# Generated by Django 4.1.2 on 2024-06-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('idTrabajo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTrabajo', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(max_length=200)),
                ('materiales', models.CharField(max_length=80)),
                ('imagenes', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
