# Generated by Django 4.1.2 on 2024-06-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayoMakween', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='nombreMecanico',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
