# Generated by Django 4.1.2 on 2024-06-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayoMakween', '0002_trabajo_nombremecanico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('precioProducto', models.IntegerField()),
                ('marcaProducto', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='imagenes',
            field=models.ImageField(upload_to='images'),
        ),
    ]
